apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: microbrewery
  name: microbrewery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: microbrewery
    spec:
      containers:
      - image: localhost:5000/microbrewery:0.1
        name: mango
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
